services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: bankcards
      POSTGRES_USER: hello
      POSTGRES_PASSWORD: world
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U hello -d bankcards"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build: .
    container_name: spring_app
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/bankcards
      SPRING_DATASOURCE_USERNAME: hello
      SPRING_DATASOURCE_PASSWORD: world
    ports:
      - "8888:8888"
    depends_on:
      postgres:
        condition: service_healthy
    restart: always

volumes:
  pgdata: